name = "MyServerPack"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50f6ec8ee0721de49a4aecb21b40d2e3e07041f8dc779845e21a14820824e5bd"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
