name = "MyServerPack"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e934f0d6d546a9fb3f67f4d0918fbe3facca303c9427db8bc9e58a55970614b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
