name = "MyServerPack"
author = "Me"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0b452a5a503481f145f0d71b6a72fb3138227dbedbb82afc04eb04932028d12"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
